### ISSUE TITLE
刷新数据时提示 “Error: ID 为 cnf_ZC0 的元素已被注册”

### ISSUE THREAD

**Issue by Yanjiachan** [LeekHub/leek-fund#299]
- CN Future删除全部数据之后仍然显示个数为(2)
![image](https://user-images.githubusercontent.com/25785265/160513480-17299bb5-48b8-40b7-a12d-bc2868b3f8b9.png)

- 然后刷新数据，显示“Error: ID 为 cnf_ZC0 的元素已被注册”
```js
Error: ID 为 cnf_ZC0 的元素已被注册
	at u.createAndRegisterTreeNode (c:\Users\a\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:63150)
	at c:\Users\a\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:61627
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 1)
	at async u.fetchChildrenNodes (c:\Users\a\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:61482)
```

**Comment by Yanjiachan** [comment]
settings.json中删除了相关元素就不报错了。
